[package]
name = "redact"
version = "0.0.10"
authors = ["Ethan Brierley <ethanboxx@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
description = """
A simple library for keeping secrets out of logs.
"""
documentation = "https://docs.rs/redact/"
repository = "https://github.com/eopb/redact"
edition = "2021"
exclude = [".github"]

[features]
default = ["std"]
# impl std::error::Error for Secret<E> where E: Error
std = []

[dependencies]
serde = { version = "1.0", optional = true, default-features = false }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }

[package.metadata.docs.rs]
all-features = true

