name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build with features
      run: cargo build --all-features --verbose
    - name: Build without features
      run: cargo build --no-default-features --verbose
    - name: Run tests
      run: cargo test --verbose
